[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "The_One_God"
versionNumber = "1.0.0"
description = "Allows you to configure the boon drops to be specifically one Olympian God."
websiteUrl = "https://github.com/excellent-ae/zannc-The_One_God"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
SGG_Modding-ModUtil = "4.0.1"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# Remove if unneeded
# [[build.copy]]
# source = "./packages"
# target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
